server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
   
    
  application:
    name: USER-SERVICE
    
    
  config:
    import: configserver:http://localhost:8085
   
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

#  profiles:
#    active:
#    - prod


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#  # By default true. no need to add further two
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
      
      