server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
#    driver-class-name: automatically selected. 
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    
eureka:
  instance:
    prefer-ip-address: true
  client:
  # By default true. no need to add further two
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka